### PR TITLE
feat(rules): provide proprietary license preset

### PR DESCRIPTION
**Pull request by vsgoulart**
[We need a new license for Cloud projects](https://docs.google.com/document/d/1Pl0qyIpn5sF4uLvxl0Y92aW3Lu6TWSB38b44T4zKN4E/edit)

### CODE REVIEW

**Review by santanaluiz — APPROVED** [review]

**Comment by santanaluiz** [comment]
looks fine, but isn’t just a new version of the commercial?

**Comment by vsgoulart** [comment]
> looks fine, but isn’t just a new version of the commercial?

I decided to create a new license because the old one specifically mentions `commercial license` and the new one `proprietary license`.
I'm also not sure if other projects still use the old license, if we just replace the license text we'll have to verify if it's ok to completely replace it.

**Comment by nikku** [comment]
Please clarify [this](https://github.com/camunda/eslint-plugin-camunda-licensed/pull/7#issuecomment-1084456861).

If we plan to upgrade everything, i.e. also Camunda Modeler and friends in the near future then updating the license + releasing a major version is the thing; if we plan to have both separate for a longer time, then the what @vsgoulart proposes is the way to go.

**Comment by nikku** [comment]
From what the document reads this is a new license.

**Review by nikku — COMMENTED** [review]
Looks good otherwise. Cool contribution :clap:

**Comment by santanaluiz** [comment]
@nikku @vsgoulart 
Seems like just an update. And it should affect the other components too

> felixmueller [11:44 AM]
> as far as I understood from Legal it is just an update to our old commercial license to make it more clear

**Comment by vsgoulart** [comment]
> @nikku @vsgoulart Seems like just an update. And it should affect the other components too
> 
> > felixmueller [11:44 AM]
> > as far as I understood from Legal it is just an update to our old commercial license to make it more clear

I'll update my PR then

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Given https://github.com/camunda/eslint-plugin-camunda-licensed/pull/7#issuecomment-1084714345 I'll release this as a fix.

**Comment by nikku** [comment]
Released with `v0.4.5`: https://github.com/camunda/eslint-plugin-camunda-licensed/blob/master/CHANGELOG.md#045.

**Pull request merged**
